#ifndef ERRORS_H
#define STICKER_ELEMENT_OUT_OF_RANGE (-1001)
#define ILLEGAL_CUBIE_SEEN (-1002)
#define MISSING_CORNER_CUBIE (-1003)
#define MISSING_EDGE_CUBIE (-1004)
#define MISSING_CENTER_CUBIE (-1005)
#define CORNER_PERMUTATION_OUT_OF_RANGE (-1006)
#define CORNER_ORIENTATION_OUT_OF_RANGE (-1007)
#define PUZZLE_ORIENTATION_NOT_SUPPORTED (-1008)
#define EDGE_PERMUTATION_OUT_OF_RANGE (-1009)
#define CENTER_ORIENTATION_NOT_SUPPORTED (-1010)
#define EDGE_ORIENTATION_OUT_OF_RANGE (-1011)
#define PERM_ELEMENT_OUT_OF_RANGE (-1012)
#define REID_ELEMENT_OUT_OF_RANGE (-1013)
#define WRONG_REID_LENGTH (-1014)
#define BAD_MOVE_FORMAT (-1015)
#define ERRORS_H
#endif
